config/routes.rb
Rails.application.routes.draw do  

  devise_for :utilisateurs, skip: :all
  devise_scope :utilisateur do
    get 'connexion' => 'devise/sessions#new', as: :new_utilisateur_session
    post 'connexion' => 'devise/sessions#create', as: :utilisateur_session
    get 'deconnexion' => 'devise/sessions#destroy', as: :destroy_utilisateur_session
    get    "inscription/cancel"  => "devise/registrations#cancel", as: :cancel_utilisateur_registration
    post   "inscription"         => "devise/registrations#create", as: :utilisateur_registration
    get    "inscription/enregistrement" => "devise/registrations#new", as: :new_utilisateur_registration
    get    "inscription/edit"    => "devise/registrations#edit", as: :edit_utilisateur_registration
    patch  "inscription"         => "devise/registrations#update"
    put    "inscription"         => "devise/registrations#update"
    delete "inscription"         => "devise/registrations#destroy"
  end
  
  
  resources :utilisateurs, :controller => "utilisateurs"
  root 'welcome#index'

  get 'test/style' => 'style#index'

end

app/models/utilisateur.rb
class Utilisateur < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates_confirmation_of :email, message: "Les mails doivent etre identiques"
  validates_presence_of :nom, :prenom, :email_confirmation, :password_confirmation
  validates_uniqueness_of :email
end

app/controllers/utilisateurs/confirmations_controller.rb
class Utilisateurs::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/utilisateurs/omniauth_callbacks_controller.rb
class Utilisateurs::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when omniauth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/utilisateurs/passwords_controller.rb
class Utilisateurs::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/utilisateurs/registrations_controller.rb
class Utilisateurs::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
   def new
     super
   end

  # POST /resource
   def create
     @utilisateur.add_role("utilisateur");
     super
     #@utilisateur.add_role("utilisateur");
   end

   # GET /resource/edit
   def edit
     super
     @utilisateur
   end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # You can put the params you want to permit in the empty array.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  protected 
  
   def after_sign_up_path_for(resource)
     session[:previous_url] || root_path
   end
   
   def after_sign_in_path_for(resource)
     session[:previous_url] || root_path
   end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/utilisateurs/sessions_controller.rb
class Utilisateurs::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/utilisateurs/unlocks_controller.rb
class Utilisateurs::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/utilisateurs_controller.rb
class UtilisateursController < ApplicationController
  #load_and_authorize_resource :through => :current_user
  # GET /utilisateurs
  # GET /utilisateurs.json
  def index
    #@utilisateurs = Utilisateur.exclude?(:id => current_utilisateur.id)
    @utilisateurs = Utilisateur.all
  end
  
  # GET /utilisateurs/1
  # GET /utilisateurs/1.json
  def show
    @utilisateur = Utilisateur.find(params[:id])
  end
  
  def new
    @utilisateur = Utilisateur.new
    
    
    #if @utilisateur.save
      #    format.html { redirect_to @utilisateur, notice: 'User was successfully created.' }
      #    format.json { render :show, status: :created, location: @utilisateur }
      #  end
    end
  
  def create
    
    @utilisateur = Utilisateur.new(utilisateur_params)
    #utilisateur = Utilisateur.new()
    
    #@utilisateur = utilisateur
    if @utilisateur.save
      @utilisateur.add_role :utilisateur
      flash[:notice] = "Successfully created User." 
      redirect_to @utilisateur
    else
      render :action => 'new'
    end
  end
  
  # GET /utilisateurs/1/edit
  def edit
    @utilisateur = Utilisateur.find(params[:id])
  end
  
  # PATCH/PUT /utilisateurs/1
  # PATCH/PUT /utilisateurs/1.json
  def update
  @utilisateur = Utilisateur.find(params[:id])
 
  if @utilisateur.update(utilisateur_params)
    redirect_to @utilisateur
  else
    render 'edit'
  end
end

  def destroy
  @utilisateur = Utilisateur.find(params[:id])
  @utilisateur.destroy
 
  redirect_to utilisateurs_path
end
 
private
  def utilisateur_params
    params.require(:utilisateur).permit(:email, :email_confirmation, :password, :password_confirmation,  :nom, :prenom)
  end
  
  
  protected 
  
   def after_sign_up_path_for(resource)
     redirect_to utilisateurs_path
   end
   
   def after_sign_in_path_for(resource)
     redirect_to utilisateurs_path
   end
end

app/helpers/utilisateurs_helper.rb
module UtilisateursHelper
end

app/views/utilisateurs/_form.html.erb
<%= form_for(@utilisateur) do |f| %>
  <% if @utilisateur.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@utilisateur.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @utilisateur.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :email_confirmation %><br />
    <%= f.email_field :email_confirmation%>
  </div>

  <div class="field">
    <%= f.label :password %><br />
    <% if @validatable %>
    <em>(<%= @minimum_password_length %> caractères minimum)</em>
    <% end %><br />
    <%= f.password_field :password, autocomplete: "off" %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "off" %>
  </div>

  <div class="field">
    <%= f.label :nom %><br />
    <%= f.text_field :nom, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :prenom %><br />
    <%= f.text_field :prenom, autofocus: true %>
  </div>
    
  <div class="actions">
    <%= f.submit "Créer"%>
  </div>
<% end %>

app/views/utilisateurs/edit.html.erb
<% provide(:title, "Edition de l'utilisateur") %>

<h1>Edition de l'utilisateur</h1>

<%= render 'form' %>

<%= link_to 'Show', @utilisateur %> |
<%= link_to 'Back', utilisateurs_path %>

app/views/utilisateurs/index.html.erb
<h1>Liste des utilisateurs</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Email</th>
      <th>Nom</th>
      <th>Prenom</th>
      <th>Date Création</th>
      <th>Date Modification</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @utilisateurs.each do |utilisateur| %>
      <tr>
        <td><%= utilisateur.id %></td>
        <td><%= utilisateur.email %></td>
        <td><%= utilisateur.nom %></td>
        <td><%= utilisateur.prenom %></td>
        <td><%= utilisateur.dateCreation %></td>
        <td><%= utilisateur.dateModification %></td>
         <td><%= link_to 'Show', utilisateur %></td>
        <td><%= link_to 'Edit', edit_utilisateur_path(utilisateur) %></td>
        <td><%= link_to 'Destroy', utilisateur, method: :delete, data: { confirm: 'Etes-vous sûr?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nouvel utilisateur', new_utilisateur_path %>

app/views/utilisateurs/new.html.erb
<h1>Nouvel utilisateur</h1>

<%= render 'form' %>

<%= link_to 'Retour', utilisateurs_path %>

app/views/utilisateurs/show.html.erb
<p id="notice"><%= notice %></p>

<% if false%> <p>
  <strong>Mot de passe encrypté:</strong>
  <%= @utilisateur.encrypted_password %>
</p><% end %>

<p>
  <strong>Email:</strong>
  <%= @utilisateur.email %>
</p>

<p>
  <strong>Nom:</strong>
  <%= @utilisateur.nom %>
</p>

<p>
  <strong>Prenom:</strong>
  <%= @utilisateur.prenom %>
</p>

<p>
  <strong>Date création:</strong>
  <%= @utilisateur.dateCreation %>
</p>

<p>
  <strong>Date modification:</strong>
  <%= @utilisateur.dateModification %>
</p>
<%= link_to 'Edit', edit_utilisateur_path(@utilisateur) %> |
<%= link_to 'Back', utilisateurs_path %>